[environments.dev]
theme = "123456789012"
store = "my-store"
password  = "shptka_123456"

[environments.satge]
theme = "123456789012"
store = "another-store"
password  = "shptka_123456"
#path = "./dist"
#ignore = ["sections/announcement-bar.liquid", "sections/header.liquid"]
#output = "json"
#live = true
#allow-live = true